TELEGRAM_BOT_TOKEN=
TELEGRAM_ADMIN_USERS=
VPN_CONFIGURATION_FILE=
VPN_PUBLIC_KEY=
SERVER_PUBLIC_IP=
DNS_SERVERS=
DATABASE_NAME_PRINCIPAL=
DATABASE_NAME_PRINCIPAL_STATE=
DATABASE_NAME_PRINCIPAL_HANDLERS=
DATABASE_PATH=